### ISSUE TITLE
Help with integrating OsmAnd Api into App

### ISSUE THREAD

**Issue by joaand** [osmandapp/osmand-api-demo#1]
I need some help with integrating the API into a App I am trying to make.
I am trying to build an Android App with Android Studio. I added the OsmAndHelper.java to the folder where my MainActivity.java is. I am trying to call the Navigate method from inside my MainActivity.

I am using:
`OsmAndHelper.navigate( startName,  startLat,  startLon,  destName,  destLat,  destLon,  profile,  force);`
But I get the error: "cannot resolve symbol 'navigate'"

I am sure I am doing something wrong here calling the method but I have no clue. I am coming from a C# background so Java is new to me.
Any help is very much appreciated.

**Comment by vshcherb** [comment]
It is hard to say what's wrong and looks as an issue for Java development and not related to OsmAnd API.
I think you should see somewhere compilation error.

**Comment by vshcherb** [comment]
P.s. this project might be a bit complicated cause it is written in Kotlin not in java unfortunately I can't say more about it yet. It is just example which was written year ago.
