### ISSUE TITLE
Firing the intent from a hybrid framework

### ISSUE THREAD

**Issue by franciskim** [osmandapp/osmand-api-demo#10]
Hi there, I'm developing an app in Ionic 2 - is the intent a native Java call? Or can it be a URI? I guess if it's not able to be triggered via a URI then the only option I believe is to create a Cordova plugin. Any guidance would be appreciated. (I tried the OsmAnd support email but was advised to ask here).

**Comment by vshcherb** [comment]
Yes it can be URI, though you can easy check in https://github.com/osmandapp/osmand-api-demo/blob/master/app/src/main/java/net/osmand/osmandapidemo/MainActivity.kt

**Comment by andreddosantos** [comment]
Hello @franciskim can you share how do you manage to trigger osmand through URI? 
I'm not sure how to interact with the osmand App from the IONIC app.

Can you help?
Thnks André
