### ISSUE TITLE
Streaming next turn information

### ISSUE THREAD

**Issue by joschiealder** [osmandapp/osmand-api-demo#15]
Hi,

is there any way to get the next turn type and the distance to the next turn in a more "streaming" way than calling it in an intent? I currently call it way too often and this causes the OsmAnd app or my app to crash.

I need to check if the next turn type is less than 50 meters away and than do my own app's stuff (sending a BLE command).

Any help appreciated :)

Thanks, Joschie

**Comment by vshcherb** [comment]
IT should be part of AIDL interface.
