### ISSUE TITLE
OpenStreetMap labels stream

### ISSUE THREAD

**Issue by lucumon** [osmandapp/osmand-api-demo#24]
Hi! I was thinking of developing a n OsmAnd plugin for extended traffic signs rendering but, I have a problem. I think that OsmAnd only downloads the specific map data that it draws and anything more, so de api couldn't provide me the traffic signs labels on real-time navigation. Could you please confirm that?
I was thinking to ask osmand for coordinates and then lookup osm for traffic sign keys as a workaround, but that would be much more complex.
Thank you very much.

**Comment by vshcherb** [comment]
Well OsmAnd data is limited but it probably has most of  traffic signs, if you think about custom rendering style it is one thing if you think about access OSM-data prepared by OsmAnd then there is no such API

**Comment by lucumon** [comment]
I think that what I wanted to do is impossible with the current api. I thought that it could be an useful feature to be able to see on osmand, all existent traffic signs, in the same way as crossing ones are showed and, on the indications field, see destination signs. I think that the api would not give me this labels from osm, and also I think that I wouldn't be able to print custom features on osmand.
I think that I reached a dead point, where maybe the optimal solution is try to code a modification on osmand itself for being released later by you.

**Comment by vshcherb** [comment]
Probably, of course it is easier to modify osmand code initially and then discuss whether it could be make a plugin or should into OsmAnd itself. Then it will be clear what needs to be achieved from technical perspective.
Anyway I would modify OsmAnd-code itself initially
