### ISSUE TITLE
Command NAVIGATE ignores parameters

### ISSUE THREAD

**Issue by adolgiy** [osmandapp/osmand-api-demo#40]
If I use filled URI with NAVIGATE command, I got blank map screen. 
```
osmand.api://navigate?start_lon=37.529304&dest_lat=51.582987&dest_name=г Саратов&profile=default&start_lat=55.996982&dest_lon=46.1287952&force=false
```

If i use empty URI - I got blank navigation sheet with source and destination to set.
```
osmand.api://navigate
```

So... What can I fix to make sheet properly bind URI params?

OsmAnd+ 3.8.4

**Comment by Chumva** [comment]
You have to use one of the profiles used in routing. profile=default - browse map, it doesn`t have routing.

**Comment by Chumva** [comment]
For OsmAnd+ 3.8.4 there are only three profiles supported - https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/src/net/osmand/plus/helpers/ExternalApiHelper.java#L163 but after this request https://github.com/osmandapp/OsmAnd/pull/10307 there will be all profiles supported which have routing.
