### ISSUE TITLE
Encapsulating navigation task in custom Android App

### ISSUE THREAD

**Issue by nsarzimadidini** [osmandapp/osmand-api-demo#42]
I'd like to know if it is possible to launch an OsmAnd navigation task inside an Android App. In particular, I'd like to visualize the interactive map and overlap part of it with some buttons, in order to perform custom procedures at any moment during the navigation process. Is this kind of operation supported by Android APIs?
Thanks for your kind attention.

**Comment by vshcherb** [comment]
Currently we're building a new documentation about what's possible to do & how. Probably it will be more detailed though we don't polished integration builtin integration yet.

https://osmand.net/build_it - old documentation.
