### ISSUE TITLE
AIDL OsmAndAidHelper.java import issues

### ISSUE THREAD

**Issue by jepongski** [osmandapp/osmand-api-demo#45]
I am getting issues on using "com.github.osmandapp:Osmand:master-SNAPSHOT" as it is getting timed out when building the app. I tried to use the "com.github.osmandapp:osmand:2.0.0" but the AIDL helper is getting issues where some classes are unable to import, such as MapMarginsParams, ProfileSettingsParams, ABlockedRoad, AddBlockedRoadParams, RemoveBlockedRoadParams etc. is there something that i missed? or can we check the  url for master-snapshot why am i not able to access it?

OsmAndAidlHelper.java:23: error: cannot find symbol
import net.osmand.aidlapi.customization.MapMarginsParams;
                                       ^
  symbol:   class MapMarginsParams
  location: package net.osmand.aidlapi.customization

**Comment by vshcherb** [comment]
2.0 is probably outdated, so you need to use "com.github.osmandapp:Osmand:master-SNAPSHOT"
