### ISSUE TITLE
App crash: on navigation

### ISSUE THREAD

**Issue by roufsyed99** [osmandapp/osmand-api-demo#60]
Device Spec: 
Samsung M30s
Android 11
Root access: No

The OsmAnd-map-sample app crashes in full map activity on starting navigation for the desired destination.

Log:
https://pastebin.com/AZXRaRtp

**Comment by fbl-nordcom** [comment]
@roufsyed99 I'm having the same problem. Did you manage to solve it?

**Comment by vshcherb** [comment]
Do you see it on a compiled version https://download.osmand.net/latest-night-build/OsmAnd-map-sample.apk?

**Comment by fbl-nordcom** [comment]
The app crashes when starting navigation on the compiled version too.

**Comment by vshcherb** [comment]
Confirming app crashes on API Simple Points / Navigation and also app crashes during navigation on Full Map Activity
