### ISSUE TITLE
[feature request] Use API from a background service

### ISSUE THREAD

**Issue by jay3** [osmandapp/osmand-api-demo#7]
Hello,

My need would be to start/stop gpx recording from another app running in the background (more precisely from a Service).
Do you have any plan to add Android Interprocess Communication as mention in the documentation? Or an API based on broadcast intents (instead of starting an activity)?

Thanks by advance
Jay

PS: I've tried to modify the api (startActivityForResult being not available for service, I've tested to replace it by calling startActivity on a Context). I've obtained some results, but if I use closeAfterCommand=true, osmand crashes).
=> I guess it is not the right way to do it

**Comment by vshcherb** [comment]
The request is valid at least I don't see that method in https://github.com/osmandapp/osmand-api-demo/blob/master/app/src/net/osmand/aidl/IOsmAndAidlInterface.aidl. 

Today you can use only intent (intent will not switch the application - special option) though start/stop is missing. We will add it next release.

**Comment by vshcherb** [comment]
The issue is moved to OsmAnd

**Comment by jay3** [comment]
Thanks for your answer.
I guess AIDL api calls work only with OsmAnd+ ?

**Comment by vshcherb** [comment]
Nope, with every version.
