### ISSUE TITLE
Error - Osmand service NOT bind 

### ISSUE THREAD

**Issue by jaccky** [osmandapp/osmand-api-demo#73]
Hi, 
I forked the api demo project, built it successfully using github Actions, and installed it on my Android phone .
when I start the demo app, I get an error "Osmand service NOT bind" and a popup that redirects me to the google play page of osmand.

The error happens even if the Osmand app is started and in background, I also tried to buy a monthly subscription, just in the case, but the problem persists...
Could you help me to track down the problem ? 
![Screenshot_2024-02-05-17-45-12-16_52d609a20e8527984c5ca358d2cee647](https://github.com/osmandapp/osmand-api-demo/assets/6945531/6a65ca92-7550-4004-8f69-f27a4c2f683e)

**Comment by vshcherb** [comment]
You can select which ap to bind OsmAnd+ or OsmAnd below (or in the code). They have different package ids net.osmand and net.osmand.plus You can also try https://download.osmand.net/latest-night-build/OsmAnd-android-full-arm64.apk
